apiVersion: apps/v1
kind: Deployment
metadata:
name: todoapp-deployment
namespace: mateapp
spec:
replicas: 2
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
selector:
matchLabels:
app: todoapp
template:
metadata:
labels:
app: todoapp
spec:
containers:
- name: todoapp
image: aezakmi683/todoapp:3.0.0
ports:
- containerPort: 8000
resources:
requests:
cpu: "100m"
memory: "128Mi"
limits:
cpu: "500m"
memory: "512Mi"
